apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api-deployment
  namespace: cluster-projet
  labels:
    app: jobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-api-pod
  template:
    metadata:
      labels:
        app: jobs-api-pod
    spec:
      containers:
      - name: jobs-api
        image: nico916/projectv3-jobs-api:v1
        ports:
          - containerPort: 80
        env:
        - name: ConnectionString
          value: Server=database;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
        - name: HostRabbitmq
          value: rabbitmq-service
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs
  namespace: cluster-projet
spec:
  selector:
    app: jobs-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP