---
apiVersion: v1
kind: Service
metadata:
  name: service-identity-api
spec:
  selector:
    app: identity-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP