apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  namespace: cluster-projet
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api-pod
  template:
    metadata:
      labels:
        app: identity-api-pod
    spec:
      containers:
        - image: nico916/projectv2-identity-api:v1
          name: identity-api
          ports:
            - containerPort: 80
          env:
            - name: RedisHost
              value: user-data-api:6379
            - name: HostRabbitmq
              value: rabbitmq-service
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-api-identity
  namespace: cluster-projet
spec:
  selector:
    app: identity-api
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP